Iterate on git aliases error handling.

diff --git a/git/functions/git-ancestor b/git/functions/git-ancestor
--- a/git/functions/git-ancestor
+++ b/git/functions/git-ancestor
@@ -8,6 +8,12 @@
 # is done in lexicographically.
 #
 
+# abort if not in git directory
+if ! git rev-parse --git-dir > /dev/null 2>&1; then
+  echo "Aborting. Not in a git repository."
+  exit 1
+fi
+
 # only exclude input regex from matches
 exclusion="$1"
 if [ -z "$exclusion" ]; then
diff --git a/git/functions/git-killme b/git/functions/git-killme
--- a/git/functions/git-killme
+++ b/git/functions/git-killme
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# abort if not in git directory
+if ! git rev-parse --git-dir > /dev/null 2>&1; then
+  echo "Aborting. Not in a git repository."
+  exit 1
+fi
+
 branch="$(git rev-parse --abbrev-ref HEAD)"
 fallback="darren" # branch to transition to
 
diff --git a/git/functions/git-pullme b/git/functions/git-pullme
--- a/git/functions/git-pullme
+++ b/git/functions/git-pullme
@@ -5,6 +5,12 @@
 # against the nearest ancestor branch that is not the currently pushed branch.
 #
 
+# abort if not in git directory
+if ! git rev-parse --git-dir > /dev/null 2>&1; then
+  echo "Aborting. Not in a git repository."
+  exit 1
+fi
+
 # specify the root url
 source="https://github.com"
 
